// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	NOTIFICATIONS: DurableObjectNamespace<import("./src/index").Notifications>;
	DB: D1Database;
}
